# Generated by Django 5.2.7 on 2025-11-17 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hallgato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=100)),
                ('kar', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hallgató',
                'verbose_name_plural': 'Hallgatók',
            },
        ),
        migrations.CreateModel(
            name='Tanar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tanár',
                'verbose_name_plural': 'Tanárok',
            },
        ),
        migrations.CreateModel(
            name='Kurzus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=200)),
                ('leiras', models.TextField()),
                ('tanar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kurzusok', to='tananyag.tanar')),
            ],
            options={
                'verbose_name': 'Kurzus',
                'verbose_name_plural': 'Kurzusok',
            },
        ),
        migrations.CreateModel(
            name='HallgatoKurzus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jegy', models.IntegerField(default=0)),
                ('hallgato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tananyag.hallgato')),
                ('kurzus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tananyag.kurzus')),
            ],
            options={
                'verbose_name': 'Hallgató kurzusa',
                'verbose_name_plural': 'Hallgatók kurzusai',
                'unique_together': {('hallgato', 'kurzus')},
            },
        ),
    ]
