# Generated by Django 5.2.7 on 2025-11-04 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hallgato',
            fields=[
                ('felhasznalo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nev', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kurzus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=200)),
                ('leiras', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tanar',
            fields=[
                ('felhasznalo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nev', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HallgatoKurzus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jegy', models.IntegerField()),
                ('hallgato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tananyag.hallgato')),
                ('kurzus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tananyag.kurzus')),
            ],
            options={
                'unique_together': {('hallgato', 'kurzus')},
            },
        ),
        migrations.AddField(
            model_name='hallgato',
            name='kurzusok',
            field=models.ManyToManyField(through='tananyag.HallgatoKurzus', to='tananyag.kurzus'),
        ),
        migrations.AddField(
            model_name='kurzus',
            name='tanar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tananyag.tanar'),
        ),
    ]
